version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12
    filters:
      branches:
        only:
          - master
    steps:
      - add_ssh_keys:
        fingerprints:
          - "f6:81:b7:24:86:07:78:df:5e:ba:28:dd:5f:1e:4f:ba"
      - checkout
      - restore_cache:
          keys:
            - dependencies_imooc
      - run:
          name: Install
          command: npm install
      - save_cache:
          key: dependencies_imooc
          paths:
            - node_modules
      - run:
          name: Build
          command: npm run build
      - run:
          name: Prepare Shell commands
          # shell chmod + x 赋予执行权限
          # 执行 shell 脚本
          command: chmod + x scripts/deploy.sh
      - run:
          name: Run Deploy to GitHub Pages
          command: ./scripts/deploy.sh
